language: python
dist: trusty

python:
  - 3.5
  - 3.6
os:
  - linux
env:
  global:
    - PYTHON=python3
    - PIP=pip3
    - CPPFLAGS="-Wall -Werror"
    - BFG_EXTRA_TESTS="gcj mingw-cross"
  matrix:
    - CC=gcc CXX=g++
    - CC=clang CXX=clang++

matrix:
  include:

    # Python 3.7 builds

    # gcj is busted in xenial
    - python: 3.7
      os: linux
      dist: xenial
      env: CC=gcc CXX=g++ BFG_EXTRA_TESTS="mingw-cross"
      before_install: &xenial-before-install
        - set -e
        - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        - unset _JAVA_OPTIONS
    - python: 3.7
      os: linux
      dist: xenial
      env: CC=clang CXX=clang++ BFG_EXTRA_TESTS="mingw-cross"
      before_install: *xenial-before-install

    # macOS builds

    - language: generic
      python: 3.7
      os: osx
      env: >
        CC=clang CXX=clang++ YACC=/usr/local/opt/bison/bin/bison
        BFG_SKIPPED_TESTS=scala BFG_EXTRA_TESTS=nil
      before_install:
        - set -e
        - shell_session_update() { :; }
        - brew update
        - brew unlink python@2
        - brew upgrade python3
        - brew install bison libogg ninja
        - brew link qt5 --force
        - cp test/scripts/sitecustomize.py .

    # bdist_wheel builds

    - python: 3.7
      os: linux
      dist: xenial
      env: JOB=bdist_wheel
      addons:
        apt:
          packages: []
      install: true
      script:
        - python setup.py bdist_wheel
        - pip install dist/*.whl
        - "! pip show pysetenv"
        - pip show patchelf-wrapper
      after_success:
        - true

    # Linting

    - python: 3.7
      os: linux
      dist: xenial
      env: JOB=lint
      addons:
        apt:
          packages: []
      script: ${PYTHON} setup.py lint
      after_success:
        - true

addons:
  apt:
    packages:
      - bison
      - default-jdk
      - flex
      - freeglut3-dev
      - gcc-multilib
      - gcj-jdk
      - gfortran
      - gobjc
      - gobjc++
      - libboost-dev
      - libboost-program-options-dev
      - libgl1-mesa-dev
      - libogg-dev
      - mingw-w64
      - ninja-build
      - qt5-default
      - qtdeclarative5-dev
      - scala
cache:
  apt: true

before_install:
  - set -e
  - export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
  - unset _JAVA_OPTIONS
install:
  - git clone https://github.com/jimporter/mopack.git --branch system
  - ${PIP} install ./mopack codecov .[test]
script:
  - ${PYTHON} setup.py coverage -q
after_success:
  - codecov
